import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import loremIpsum from '../loremIpsum'
// import locations from '../locationData'
import Locations from './locations'

let API = `http://localhost:3000/api`;

export default function Home() {

  fetch(`${API}/hello`)
    .then(response => response.json())
    .then(data => console.log(data));


  return (
    <div className={styles.container}>
      <Head>
        <title>Salmon Cookies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* Welcome to <a href="https://nextjs.org">Next.js!</a> */}
          Welcome to Pats Salmon Cookies!
        </h1>

        <img src="/salmon.png" alt="salmon" id="salmon-img" />
        <a href="sales.html" className="page-links" id="sales-link">Sales Data!</a>

        <h2>About Us</h2>
        <div id="about-us-container">
          <div id="family-image-div">
            <img src="/family.jpg" alt="family" id="family" />
          </div>
          <div id="lorem-ipsum">
            <p>{loremIpsum.aboutUs}</p>
          </div>
          <img src="/chinook.jpg" alt="chinook salmon" id="chinook" />
        </div>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          <Locations />


          {/* <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr; </h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr; </h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr; </h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer>
        <address id="contact-info">
          <p>Pat Jenkins</p>
          <a href="mailto:info@patssalmoncookies.com" id="email">info@patssalmoncookies.com</a>
          <p>3106 University Street</p>
          <p>Seattle, WA, 98121</p>
          <p>Phone: 206-443-9495</p>
        </address>
        <img src="/fish.jpg" alt="fish" id="fish-school" />
      </footer>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
